Running into this error on GCP:

pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '34.170.157.57' (timed out)
